name: Run Auth Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      NODE_ENV: test
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run Auth Tests
        run: npm run test:auth
