name: Deploy Node.js Backend to VPS

on:
  workflow_run:
    workflows: ["Run Jest Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/projects/back-lofilearn
            cd /home/projects/back-lofilearn
            git clone https://github.com/caglayagmuricerr/back-lofilearn.git . || true
            git pull origin main
            npm install
            cat <<EOF > .env
            NODE_ENV=development
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            PORT=5000
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            SMTP_HOST=${{ secrets.SMTP_HOST }}
            SMTP_USER=${{ secrets.SMTP_USER }}
            SMTP_PASS=${{ secrets.SMTP_PASS }}
            SMTP_PORT=587
            SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            EOF
            if pm2 describe back-lofilearn > /dev/null 2>&1; then
              pm2 restart back-lofilearn
            else
              pm2 start npm --name back-lofilearn -- start
            fi
            pm2 save
