name: Deploy Node.js Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/projects/back-lofilearn
            cd /home/projects/back-lofilearn
            git clone https://github.com/caglayagmuricerr/back-lofilearn.git . || true  # Clone if first time
            git pull origin main
            npm install
            pm2 start server.js --name back-lofilearn || pm2 restart back-lofilearn
            pm2 save
