name: Lint Changed Files on Push

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: get_changed_files
        run: |
          git fetch origin main
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E '\.(js|json|md)$' | xargs)
          echo "changed_files=${CHANGED}" >> $GITHUB_OUTPUT

      - name: Lint changed files
        if: steps.get_changed_files.outputs.changed_files != ''
        run: |
          echo "Linting files: ${{ steps.get_changed_files.outputs.changed_files }}"
          npx eslint ${{ steps.get_changed_files.outputs.changed_files }}
